# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: Default
  # vmImage: ubuntu-latest
  # Agent name: MRP

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line scrip'
# - script: |
#     echo Add other tasksto build, test, and deploy your project
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi line script'
- checkout: self
  fetchDepth: 1
- task: Npm@1
  displayName: npm install
  inputs:
    verbose: false
- task: Npm@1
  displayName: npm build
  inputs:
    command: custom
    verbose: false
    customCommand: run build
# # - task: PublishBuildArtifacts@1
# #   inputs:
# #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
# #     ArtifactName: 'drop'
# #     publishLocation: 'Container'